export const Types = {
    CREATE_ORDER: "CREATE_ORDER",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAILD: "CREATE_ORDER_FAILD",
    CREATE_ORDER_RESET: "CREATE_ORDER_RESET",

    ORDER_PAY: "ORDER_PAY",
    ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
    ORDER_PAY_FAILD: "ORDER_PAY_FAILD",
    ORDER_PAY_RESET: "ORDER_PAY_RESET",

    ORDER_DTAILS: "ORDER_DTAILS",
    ORDER_DTAILS_SUCCESS: "ORDER_DTAILS_SUCCESS",
    ORDER_DTAILS_FAILD: "ORDER_DTAILS_FAILD",

    ORDER_HISTORY: "ORDER_HISTORY",
    ORDER_HISTORY_SUCCESS: "ORDER_HISTORY_SUCCESS",
    ORDER_HISTORY_FAILD: "ORDER_HISTORY_FAILD",

    ORDER_HISTORY_ADMIN: "ORDER_HISTORY_ADMIN",
    ORDER_HISTORY_ADMIN_SUCCESS: "ORDER_HISTORY_ADMIN_SUCCESS",
    ORDER_HISTORY_ADMIN_FAILD: "ORDER_HISTORY_ADMIN_FAILD",

    ORDER_DELETE: "ORDER_DELETE",
    ORDER_DELETE_SUCCESS: "ORDER_DELETE_SUCCESS",
    ORDER_DELETE_FAILD: "ORDER_DELETE_FAILD",
    ORDER_DELETE_RESET: "ORDER_DELETE_RESET",

    ORDER_DELIVERE: "ORDER_DELIVERE",
    ORDER_DELIVERE_SUCCESS: "ORDER_DELIVERE_SUCCESS",
    ORDER_DELIVERE_FAILD: "ORDER_DELIVERE_FAILD",
    ORDER_DELIVERE_RESET: "ORDER_DELIVERE_RESET",
}