export const CartTypes = {
    ADD_ITEM_CART: "ADD_ITEM_CART",
    ADD_ITEM_CART_SUCCESS: "ADD_ITEM_CART_SUCCESS",
    ADD_ITEM_CART_FAILD: "ADD_ITEM_CART_FAILD",

    REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
    SAVE_SHIPPIN_ADDRESS: "SAVE_SHIPPIN_ADDRESS",
    SAVE_PAYMENT_METHOD: "SAVE_PAYMENT_METHOD",
    CART_EMPTY: "CART_EMPTY",
    CART_ADD_ITEM_FAILD: "CART_ADD_ITEM_FAILD",
}