export const Types = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",

    FETCH_PRODUCT_DTAILS: "FETCH_PRODUCTS_DTAILS",
    FETCH_PRODUCT_DTAILS_SUCCESS: "FETCH_PRODUCTS_DTAILS_SUCCESS",
    FETCH_PRODUCT_DTAILS_FAILED: "FETCH_PRODUCTS_DTAILS_FAILED",

    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILED: "ADD_PRODUCT_FAILED",
    ADD_PRODUCT_RESET: "ADD_PRODUCT_RESET",

    EDIT_PRODUCT: "EDIT_PRODUCT",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAILD: "EDIT_PRODUCT_FAILD",
    EDIT_PRODUCT_RESET: "EDIT_PRODUCT_RESET",

    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAILD: "DELETE_PRODUCT_FAILD",
    DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET",

    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILD: "FETCH_CATEGORIES_FAILD",

    ADD_COMMENT: "ADD_COMMENT",
    ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
    ADD_COMMENT_FAILD: "ADD_COMMENT_FAILD",
    ADD_COMMENT_RESET: "ADD_COMMENT_RESET",
}