export const Types = {
    USER_SIGNIN: "USER_SIGNIN",
    USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAILD: "USER_SIGNIN_FAILD",
    USER_SIGNOUT: "USER_SIGNOUT",

    USER_REGISTER: "USER_REGISTER",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILD: "USER_REGISTER_FAILD",

    USER_PROFILE: "USER_PROFILE",
    USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
    USER_PROFILE_FAILD: "USER_PROFILE_FAILD",

    USER_UPDATE: "USER_UPDATE",
    USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
    USER_UPDATE_FAILD: "USER_UPDATE_FAILD",
    USER_UPDATE_RESET: "USER_UPDATE_RESET",

    USER_LIST: "USER_LIST",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAILD: "USER_LIST_FAILD",

    USER_DELETE: "USER_DELETE",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    USER_DELETE_FAILD: "USER_DELETE_FAILD",
    USER_DELETE_RESET: "USER_DELETE_RESET",

    USER_UPDATE_ADMIN: "USER_UPDATE_ADMIN",
    USER_UPDATE_ADMIN_SUCCESS: "USER_UPDATE_ADMIN_SUCCESS",
    USER_UPDATE_ADMIN_FAILD: "USER_UPDATE_ADMIN_FAILD",
    USER_UPDATE_ADMIN_RESET: "USER_UPDATE_ADMIN_RESET",

    USER_TOPSELLER_LIST: "USER_TOPSELLER_LIST",
    USER_TOPSELLER_LIST_SUCCESS: "USER_TOPSELLER_LIST_SUCCESS",
    USER_TOPSELLER_LIST_FAILD: "USER_TOPSELLER_LIST_FAILD",

    USER_ADDRESS_MAP_CONFIRM: "USER_ADDRESS_MAP_CONFIRM"
}